keywords = [
  "Investment banking",
  "brokerage",
  "wealth management",
  "financial services",
  "global financials",
  "Cryptocurrency",
  "digital assets",
  "blockchain",
  "Bitcoin",
  "Ethereum",
  "crypto exchange",
  "cryptocurrency market",
  "Streaming",
  "content creation",
  "original series",
  "movies",
  "OTT platform",
  "international growth",
  "subscriber count",
  "Shipbuilding",
  "defense",
  "military",
  "naval ships",
  "infrastructure",
  "defense contracts",
  "Aerospace",
  "technology",
  "communication systems",
  "aviation",
  "aircraft maintenance",
  "repair",
  "overhaul services",
  "airline industry",
  "German aviation",
  "cybersecurity",
  "military contracts",
  "missile defense system",
  "Banking",
  "asset management",
  "global banking",
  "finance",
  "investment services",
  "Wall Street",
  "hedge funds",
  "Athletic apparel",
  "retail",
  "yoga wear",
  "fitness",
  "lifestyle brand",
  "athleisure trend",
"war"
]